[workspace]

members = [
    # Common
    "allocate",
    "nome",
    "arrow-vs-arrow2",
    "serde",
    "share",
    "rust-crc32fast"
]

[profile.release]
debug = true

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"
